mod distributed {
    pub(super) use super::super::distributed::*;
}

mod distributed_consensus {
    pub(super) use super::super::distributed_consensus::{
        ConsensusMembershipChange, ConsensusMembershipChangeRequest,
        ConsensusMembershipChangeResult, QuorumConsensus,
    };
}

mod distributed_dht {
    pub(super) use super::super::distributed_dht::{DistributedDht, MembershipDirectorySnapshot};
}

mod distributed_net {
    pub(super) use super::super::distributed_net::{DistributedNetwork, NetworkSubscription};
}

mod error {
    pub(super) use super::super::error::WorldError;
}

mod util {
    pub(super) use super::super::util::to_canonical_cbor;
}

mod membership_logic {
    include!("distributed_membership_sync/logic.rs");
}

mod shared {
    include!("../../../agent_world_consensus/src/membership.rs");
}

mod membership {
    pub(super) use super::shared::*;
}

pub use shared::*;

#[cfg(test)]
use super::distributed_consensus::{
    ConsensusMembershipChange, ConsensusMembershipChangeRequest, ConsensusMembershipChangeResult,
    QuorumConsensus,
};
#[cfg(test)]
use super::distributed_dht::MembershipDirectorySnapshot;
#[cfg(test)]
use super::error::WorldError;

#[rustfmt::skip]
pub use reconciliation::{
    FileMembershipRevocationAlertSink, FileMembershipRevocationScheduleStateStore, InMemoryMembershipRevocationAlertSink,
    InMemoryMembershipRevocationScheduleCoordinator, InMemoryMembershipRevocationScheduleStateStore,
    MembershipRevocationAlertDedupPolicy, MembershipRevocationAlertDedupState, MembershipRevocationAlertPolicy,
    MembershipRevocationAlertSeverity, MembershipRevocationAlertSink, MembershipRevocationAnomalyAlert,
    MembershipRevocationCheckpointAnnounce, MembershipRevocationCoordinatedRunReport, MembershipRevocationReconcilePolicy,
    MembershipRevocationReconcileReport, MembershipRevocationReconcileSchedulePolicy, MembershipRevocationReconcileScheduleState,
    MembershipRevocationScheduleCoordinator, MembershipRevocationScheduleStateStore, MembershipRevocationScheduledRunReport,
};
#[rustfmt::skip]
pub use recovery::{
    FileMembershipRevocationAlertDeadLetterStore, FileMembershipRevocationAlertRecoveryStore, FileMembershipRevocationCoordinatorStateStore,
    FileMembershipRevocationDeadLetterReplayPolicyAuditStore, FileMembershipRevocationDeadLetterReplayPolicyStore,
    FileMembershipRevocationDeadLetterReplayRollbackAlertStateStore, FileMembershipRevocationDeadLetterReplayRollbackGovernanceAuditRetentionStore,
    FileMembershipRevocationDeadLetterReplayRollbackGovernanceAuditStore, FileMembershipRevocationDeadLetterReplayRollbackGovernanceRecoveryDrillAlertEventBus, FileMembershipRevocationDeadLetterReplayRollbackGovernanceRecoveryDrillAlertEventCompositeSequenceCursorStateStore, FileMembershipRevocationDeadLetterReplayRollbackGovernanceRecoveryDrillAlertStateStore, FileMembershipRevocationDeadLetterReplayRollbackGovernanceRecoveryDrillScheduleStateStore,
    FileMembershipRevocationDeadLetterReplayRollbackGovernanceStateStore,
    FileMembershipRevocationDeadLetterReplayStateStore, InMemoryMembershipRevocationAlertDeadLetterStore, InMemoryMembershipRevocationAlertRecoveryStore,
    InMemoryMembershipRevocationCoordinatorStateStore, InMemoryMembershipRevocationDeadLetterReplayPolicyAuditStore, InMemoryMembershipRevocationDeadLetterReplayPolicyStore,
    InMemoryMembershipRevocationDeadLetterReplayRollbackAlertStateStore, InMemoryMembershipRevocationDeadLetterReplayRollbackGovernanceAuditRetentionStore,
    InMemoryMembershipRevocationDeadLetterReplayRollbackGovernanceAuditStore, InMemoryMembershipRevocationDeadLetterReplayRollbackGovernanceRecoveryDrillAlertEventBus, InMemoryMembershipRevocationDeadLetterReplayRollbackGovernanceRecoveryDrillAlertEventCompositeSequenceCursorStateStore, InMemoryMembershipRevocationDeadLetterReplayRollbackGovernanceRecoveryDrillAlertStateStore, InMemoryMembershipRevocationDeadLetterReplayRollbackGovernanceRecoveryDrillScheduleStateStore,
    InMemoryMembershipRevocationDeadLetterReplayRollbackGovernanceStateStore,
    InMemoryMembershipRevocationDeadLetterReplayStateStore, MembershipRevocationAlertAckRetryPolicy, MembershipRevocationAlertDeadLetterReason,
    MembershipRevocationAlertDeadLetterRecord, MembershipRevocationAlertDeadLetterStore, MembershipRevocationAlertDeliveryMetrics,
    MembershipRevocationAlertRecoveryReport, MembershipRevocationAlertRecoveryStore, MembershipRevocationCoordinatedRecoveryRunReport,
    MembershipRevocationCoordinatorLeaseState, MembershipRevocationCoordinatorStateStore, MembershipRevocationDeadLetterReplayPolicy,
    MembershipRevocationDeadLetterReplayPolicyAdoptionAuditDecision, MembershipRevocationDeadLetterReplayPolicyAdoptionAuditRecord,
    MembershipRevocationDeadLetterReplayPolicyAuditStore, MembershipRevocationDeadLetterReplayPolicyState, MembershipRevocationDeadLetterReplayPolicyStore,
    MembershipRevocationDeadLetterReplayRollbackAlertPolicy, MembershipRevocationDeadLetterReplayRollbackAlertState,
    MembershipRevocationDeadLetterReplayRollbackAlertStateStore, MembershipRevocationDeadLetterReplayRollbackGovernanceLevel, MembershipRevocationDeadLetterReplayRollbackGovernanceArchiveDrillScheduledRunReport, MembershipRevocationDeadLetterReplayRollbackGovernanceArchiveTieredOffloadDrillAlertEventBusRunReport, MembershipRevocationDeadLetterReplayRollbackGovernanceArchiveTieredOffloadDrillAlertRunReport,
    MembershipRevocationDeadLetterReplayRollbackGovernanceAuditAggregateQueryPolicy, MembershipRevocationDeadLetterReplayRollbackGovernanceAuditAggregateQueryRecord, MembershipRevocationDeadLetterReplayRollbackGovernanceAuditAggregateQueryReport, MembershipRevocationDeadLetterReplayRollbackGovernanceAuditArchiveTier, MembershipRevocationDeadLetterReplayRollbackGovernanceAuditPruneReport, MembershipRevocationDeadLetterReplayRollbackGovernanceAuditRetentionPolicy, MembershipRevocationDeadLetterReplayRollbackGovernanceAuditRetentionStore, MembershipRevocationDeadLetterReplayRollbackGovernanceAuditTieredOffloadPolicy, MembershipRevocationDeadLetterReplayRollbackGovernanceAuditTieredOffloadReport,
    MembershipRevocationDeadLetterReplayRollbackGovernanceAuditRecord, MembershipRevocationDeadLetterReplayRollbackGovernanceAuditStore,
    MembershipRevocationDeadLetterReplayRollbackGovernancePolicy, MembershipRevocationDeadLetterReplayRollbackGovernanceRecoveryDrillReport,
    MembershipRevocationDeadLetterReplayRollbackGovernanceRecoveryDrillAlertEvent, MembershipRevocationDeadLetterReplayRollbackGovernanceRecoveryDrillAlertEventBus, MembershipRevocationDeadLetterReplayRollbackGovernanceRecoveryDrillAlertEventCompositeSequenceCursorState, MembershipRevocationDeadLetterReplayRollbackGovernanceRecoveryDrillAlertEventCompositeSequenceCursorStateStore, MembershipRevocationDeadLetterReplayRollbackGovernanceRecoveryDrillAlertEventOutcome, MembershipRevocationDeadLetterReplayRollbackGovernanceRecoveryDrillAlertPolicy, MembershipRevocationDeadLetterReplayRollbackGovernanceRecoveryDrillAlertRunReport, MembershipRevocationDeadLetterReplayRollbackGovernanceRecoveryDrillAlertState, MembershipRevocationDeadLetterReplayRollbackGovernanceRecoveryDrillAlertStateStore, MembershipRevocationDeadLetterReplayRollbackGovernanceRecoveryDrillSchedulePolicy, MembershipRevocationDeadLetterReplayRollbackGovernanceRecoveryDrillScheduledRunReport,
    MembershipRevocationDeadLetterReplayRollbackGovernanceRecoveryDrillScheduleState, MembershipRevocationDeadLetterReplayRollbackGovernanceRecoveryDrillScheduleStateStore,
    MembershipRevocationDeadLetterReplayRollbackGovernanceState,
    MembershipRevocationDeadLetterReplayRollbackGovernanceStateStore, MembershipRevocationDeadLetterReplayRollbackGuard,
    MembershipRevocationDeadLetterReplayScheduleState, MembershipRevocationDeadLetterReplayStateStore, MembershipRevocationPendingAlert,
    NoopMembershipRevocationAlertDeadLetterStore, StoreBackedMembershipRevocationScheduleCoordinator,
};

#[cfg(test)]
mod coordination_tests;
mod logic;
#[cfg(test)]
mod persistence_tests;
mod reconciliation;
mod recovery;
#[cfg(test)]
mod recovery_replay_archive_tests;
#[cfg(test)]
mod recovery_replay_federated_tests;
#[cfg(test)]
mod recovery_replay_policy_audit_tests;
#[cfg(test)]
mod recovery_replay_policy_persistence_tests;
#[cfg(test)]
mod recovery_replay_tests;
#[cfg(test)]
mod recovery_tests;
#[cfg(test)]
mod scheduler_tests;
#[cfg(test)]
mod tests;
